export const HOME = {
  emergentLink: "emergent-link",
};

export const STUDIO = {
  page: "math-studio-page",
  functionInput: "function-input",
  analyzeBtn: "analyze-btn",
  exampleBtn: (k) => `example-btn-${k}`,
  optionToggle: (k) => `option-toggle-${k}`,
  derivativeOrder: "derivative-order-input",
  integralA: "integral-a-input",
  integralB: "integral-b-input",
  plotMin: "plot-min-input",
  plotMax: "plot-max-input",
  taylorOrder: "taylor-order-input",
  taylorAround: "taylor-around-input",
  resultDomain: "result-domain",
  resultParity: "result-parity",
  resultRoots: "result-roots",
  resultExtrema: "result-extrema",
  resultInflection: "result-inflection",
  resultAsymptotes: "result-asymptotes",
  resultLimits: "result-limits",
  resultTaylor: "result-taylor",
  resultDerivatives: "result-derivatives",
  resultAntiderivative: "result-antiderivative",
  resultDefiniteIntegral: "result-definite-integral",
  resultSignTable: "result-sign-table",
  resultVariationTable: "result-variation-table",
  plotCanvas: "plot-canvas",
  historyList: "history-list",
  historyItem: (i) => `history-item-${i}`,
  clearHistory: "clear-history-btn",
};
